import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { HeroHeader } from '@/components/header';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import Providers from '@/app/[locale]/providers';
import { Toaster } from 'sonner';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
type Props = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
};
export default async function RootLayout({ children, params }: Props) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    // Load messages cho locale
    const messages = (await import(`../../messages/${locale}.json`)).default;

    return (
        <html lang={locale}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <section className="flex min-h-screen bg-zinc-50 dark:bg-zinc-900">
                        <div className="flex flex-col flex-1">
                            <HeroHeader />
                            <div className="p-6 space-y-4">
                                <Breadcrumb />
                                <Providers>{children}</Providers>
                                <Toaster />
                            </div>
                        </div>
                    </section>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
